Ember.js Test App
LoginRadius/engineering-blog-samples pull request #136
Opened 2021-12-08 12:10 UTC by raghunath-r-a

@QNNAKWUE

Please verify that this as expected, so that we can move with review/approval.

2021-12-08 12:20 UTC, QNNAKWUE commented
I confirm this to be correct.


Best regards,

Queen Nnakwue


On Wed, Dec 8, 2021 at 1:10 PM Raghunath Reddy ***@***.***>
wrote:

> @QNNAKWUE <https://github.com/QNNAKWUE>
>
> Please verify that this as expected, so that we can move with
> review/approval.
> ------------------------------
> You can view, comment on, or merge this pull request online at:
>
>   https://github.com/LoginRadius/engineering-blog-samples/pull/136
> Commit Summary
>
>    - e653867
>    <https://github.com/LoginRadius/engineering-blog-samples/pull/136/commits/e653867065b8398a838041336e12bcc9e5e89a3b>
>    Ember.js Test App
>
> File Changes
>
> (74 files
> <https://github.com/LoginRadius/engineering-blog-samples/pull/136/files>)
>
>    - *A* Emberjs/ember-auth/test-app/.eslintignore
>    <https://github.com/LoginRadius/engineering-blog-samples/pull/136/files#diff-9060e6ded72299421c26b2186dad1d9582ac5edbd403940bcc8915bc84be4c78>
>    (20)
>    - *A* Emberjs/ember-auth/test-app/.eslintrc.js
>    <https://github.com/LoginRadius/engineering-blog-samples/pull/136/files#diff-3f4f4032a8b80ddc68a8264d4a8365f53da54abcd7c382ea7842e366d50f804f>
>    (47)
>    - *A* Emberjs/ember-auth/test-app/.watchmanconfig
>    <https://github.com/LoginRadius/engineering-blog-samples/pull/136/files#diff-fb8adefbdd9d9ae93007518605cd6dfb1110bfc2df5029ab429a0edb874ab38a>
>    (3)
>    - *A* Emberjs/ember-auth/test-app/app/adapters/application.js
>    <https://github.com/LoginRadius/engineering-blog-samples/pull/136/files#diff-4bad384920a1fa5f0062a70f1b0ecd960925e309e0925af9472b19809f7f2366>
>    (29)
>    - *A* Emberjs/ember-auth/test-app/app/app.js
>    <https://github.com/LoginRadius/engineering-blog-samples/pull/136/files#diff-0d2763add510189dc0ccd76a96202a1f48cbd7eb5ce33ca24dfba0d1c074d4e6>
>    (28)
>    - *A*
>    Emberjs/ember-auth/test-app/app/authenticators/oauth2-implicit-grant.js
>    <https://github.com/LoginRadius/engineering-blog-samples/pull/136/files#diff-75f220271388d9572db0cbabbac926ae82a0f65826c595a6a0c48febe1478fe8>
>    (3)
>    - *A* Emberjs/ember-auth/test-app/app/authenticators/oauth2.js
>    <https://github.com/LoginRadius/engineering-blog-samples/pull/136/files#diff-ebfe7db07965d5ea64ee477e117a9de03327b6d71d25228c2f18c2ada83e89b7>
>    (7)
>    - *A* Emberjs/ember-auth/test-app/app/authenticators/torii.js
>    <https://github.com/LoginRadius/engineering-blog-samples/pull/136/files#diff-167c08602e2cd4307ff65da3f92f662a1441cf8ceded732203501d548c06a570>
>    (24)
>    - *A* Emberjs/ember-auth/test-app/app/components/.gitkeep
>    <https://github.com/LoginRadius/engineering-blog-samples/pull/136/files#diff-9bce5f003d759f5ec401dbecb2c049b693e89a349c907252476f07587dda4690>
>    (0)
>    - *A* Emberjs/ember-auth/test-app/app/components/login-form.js
>    <https://github.com/LoginRadius/engineering-blog-samples/pull/136/files#diff-2fa16af0fb8b14f048af819db4764c75fb6d523e22d1ab3fda787326ab751c38>
>    (52)
>    - *A* Emberjs/ember-auth/test-app/app/components/main-navigation.js
>    <https://github.com/LoginRadius/engineering-blog-samples/pull/136/files#diff-9dad962af119a7d8395f26d2de39b4ec3b8f1714e50f650e65692b7521e79e3a>
>    (13)
>    - *A* Emberjs/ember-auth/test-app/app/controllers/.gitkeep
>    <https://github.com/LoginRadius/engineering-blog-samples/pull/136/files#diff-8af901ec0014ad494a41dad7cf0b11fc4e58979ac1b814586f9a432fe6cab97a>
>    (0)
>    - *A* Emberjs/ember-auth/test-app/app/controllers/application.js
>    <https://github.com/LoginRadius/engineering-blog-samples/pull/136/files#diff-62e12c3bf1ccabedbfc4e9f4d7a65eacf153b32ac8c93ad7f6f981ce6aec29f3>
>    (9)
>    - *A* Emberjs/ember-auth/test-app/app/controllers/index.js
>    <https://github.com/LoginRadius/engineering-blog-samples/pull/136/files#diff-ceaf5db1991ad2acb9948595924a9cafe623674e167fe43e1cd08f6289ab3a12>
>    (6)
>    - *A* Emberjs/ember-auth/test-app/app/helpers/.gitkeep
>    <https://github.com/LoginRadius/engineering-blog-samples/pull/136/files#diff-d9b1dbe5c919b950ed442a81a4eb14c71a30d7b4ae84d8d59cb1ae7f52dd6fb7>
>    (0)
>    - *A* Emberjs/ember-auth/test-app/app/index.html
>    <https://github.com/LoginRadius/engineering-blog-samples/pull/136/files#diff-880c6ed76a6d708d5b0fd3130f66423466e7392940190201bc0b2e7978367a64>
>    (25)
>    - *A* Emberjs/ember-auth/test-app/app/models/.gitkeep
>    <https://github.com/LoginRadius/engineering-blog-samples/pull/136/files#diff-763b59ffc06d1f9853408b8d7030ad0ae0de4dc6106dadb0b7df4ad64cfdba71>
>    (0)
>    - *A* Emberjs/ember-auth/test-app/app/models/account.js
>    <https://github.com/LoginRadius/engineering-blog-samples/pull/136/files#diff-2a96ab8c253f6f72fca24475b9410b340f9e41065011e7fd8e9258a09c3a6a71>
>    (6)
>    - *A* Emberjs/ember-auth/test-app/app/models/post.js
>    <https://github.com/LoginRadius/engineering-blog-samples/pull/136/files#diff-e7fb7b60e5eb861032bcdc093322a77a44cd4fe92d0657b76b6d0ed65aeff2f0>
>    (6)
>    - *A* Emberjs/ember-auth/test-app/app/router.js
>    <https://github.com/LoginRadius/engineering-blog-samples/pull/136/files#diff-28eafeec66e91493696bd33901c45f1f80beb9aa9ef5ca28dffcebee1b85d19b>
>    (17)
>    - *A* Emberjs/ember-auth/test-app/app/routes/.gitkeep
>    <https://github.com/LoginRadius/engineering-blog-samples/pull/136/files#diff-2cfccfd4396f0bdd1e4baf8f965ff27ce91d19a93ee60c4dcd65f52c2ab812a8>
>    (0)
>    - *A* Emberjs/ember-auth/test-app/app/routes/application.js
>    <https://github.com/LoginRadius/engineering-blog-samples/pull/136/files#diff-249de27a20f31e317de6c134f30f2a1e2d774bc85309b5c7f096bcc28f0204df>
>    (12)
>    - *A* Emberjs/ember-auth/test-app/app/routes/auth-error.js
>    <https://github.com/LoginRadius/engineering-blog-samples/pull/136/files#diff-d7267619b7c194b15e435801d3aa4a90962a747869dd7b543e5741295ab4064e>
>    (14)
>    - *A* Emberjs/ember-auth/test-app/app/routes/callback.js
>    <https://github.com/LoginRadius/engineering-blog-samples/pull/136/files#diff-3576a4271492f69d70a810616c8ebed7f5321fb2d44a33c6f6325a81f31b2adc>
>    (18)
>    - *A* Emberjs/ember-auth/test-app/app/routes/login.js
>    <https://github.com/LoginRadius/engineering-blog-samples/pull/136/files#diff-9ba2f2efdb46bc35703540b148a868e2a9634c491c73ccefb298a5520f04dd69>
>    (10)
>    - *A* Emberjs/ember-auth/test-app/app/routes/protected.js
>    <https://github.com/LoginRadius/engineering-blog-samples/pull/136/files#diff-0e17fa275b5d01d19c0db75881f20625c83fe271dd73585fb12d18fdf4294524>
>    (14)
>    - *A* Emberjs/ember-auth/test-app/app/services/session-account.js
>    <https://github.com/LoginRadius/engineering-blog-samples/pull/136/files#diff-141ab1d9f1c476063fb54e2bd4e835a2aaf0e090121d493200748b0c91f5c408>
>    (14)
>    - *A* Emberjs/ember-auth/test-app/app/services/session.js
>    <https://github.com/LoginRadius/engineering-blog-samples/pull/136/files#diff-5000c27e833d6f9c437d532a56a4e5b4f8f462df81bcbc535bbf457840d677f3>
>    (13)
>    - *A* Emberjs/ember-auth/test-app/app/session-stores/application.js
>    <https://github.com/LoginRadius/engineering-blog-samples/pull/136/files#diff-a62b86c1fb24186c8fbf8bc76130cc89d8f75709052ce4e7d1bc9104651dc667>
>    (3)
>    - *A* Emberjs/ember-auth/test-app/app/styles/app.css
>    <https://github.com/LoginRadius/engineering-blog-samples/pull/136/files#diff-35651491ba8cd75b82dfa77409fbb10746007b6bb703ec823d62cf194ee7fd77>
>    (16)
>    - *A* Emberjs/ember-auth/test-app/app/templates/application-loading.hbs
>    <https://github.com/LoginRadius/engineering-blog-samples/pull/136/files#diff-d1e0c6e36e93910f10c1b2db7705342bfce2f5d68374724f780dd484f410e02a>
>    (3)
>    - *A* Emberjs/ember-auth/test-app/app/templates/application.hbs
>    <https://github.com/LoginRadius/engineering-blog-samples/pull/136/files#diff-c11e5209024b43083db15461a0c3ca0b1fc0a932a132baa9c06f61ccc6fc6c37>
>    (4)
>    - *A* Emberjs/ember-auth/test-app/app/templates/components/.gitkeep
>    <https://github.com/LoginRadius/engineering-blog-samples/pull/136/files#diff-96b9bb4255e13b501445852bbc6a37813edd98e5590dd6c99d20636e01a [...]

2021-12-08 12:24 UTC, raghunath-r-a commented
@nathannguyenn Please approve this code PR. FYI, this is the one earlier identified as empty, but fixed now.

2021-12-09 02:59 UTC, nathannguyenn commented on Emberjs/ember-auth/test-app/package.json
> +    "my-engine": "./packages/test-app/lib/my-engine",
the path for `"my-engine"` here is incorrect and will cause an error when doing `yarn install` - correct path is `"./lib/my-engine"`

2021-12-09 03:00 UTC, nathannguyenn requested changes
1 issue highlighted, once fixed it can be merge, everything else looks good!

2021-12-09 07:57 UTC, merged